### ISSUE TITLE
question regarding configuration 

### ISSUE THREAD

**Issue by isalirezag** [xtanitfy/tf_ssd#1]
Hi
Thanks for sharing your code.
I have a question and appreciate it if you can help me out with it.
in the configaration what is the concepr/meaning of the following variables?

steps = [8, 16, 32, 64, 100, 300]
prior_variance = [0.1, 0.1, 0.2, 0.2] 
DECAY_STEPS = 20000
aspect_ratios = [[2], [2, 3], [2, 3], [2, 3], [2], [2]]

I dont understand what is steps and prior variance and decay_steps.
Also im confused about the aspect ratio, why do we define it like [2,3]? shouldn't it be like 1:2 etc?

Thanks

**Comment by xtanitfy** [comment]
steps: 
       In every featuremap the anchor grid cell will  skip these step size.
prior_variance:
      All prior boxes's variance and mean is 0.
DECAY_STEPS:
     After the interation steps,the lr will decay.
aspect_ratios
     [2,3] means aspect_ratios[i] is (1:2),(2:1),(3:1),(1:3) and By default, a 1:1 will be added.
    [2] means aspect_ratios[i] is (1:2),(2:1) and By default, a 1:1 will be added.

**Comment by isalirezag** [comment]
@xtanitfy Thank you so much!
When you say: "prior_variance:
All prior boxes's variance and mean is 0."
So why we have prior_variance = [0.1, 0.1, 0.2, 0.2] in the code?
also by prior boxes variance you mean the variance of the elements in each prior box(anchor)?

**Comment by xtanitfy** [comment]
All prior boxes's variance is  [0.1, 0.1, 0.2, 0.2] and mean is 0.Obviously I said wrong. It's suitable for all the prediction boxes  and ground truth boxes.Anchor boxes is determined and it's no need variance and mean.
The variance and mean exists between prediction boxes and anchor boxes as  between ground truth boxes and anchor boxes .
